In [1]:
import pandas as pd
import spline
import os
import numpy as np
import matplotlib.pyplot as plt
import csv
from merge_script import modify_first_column
import math
from sklearn.decomposition import PCA
import glob
import Calculate_Feature
import os
from spline import np_move_avg

def use_pca(featuer_data, n_components=5):
    pca = PCA(n_components)
    axis_fea = pca.fit_transform(featuer_data)  # 每个样本降为n_components维
    fea = []
    for raw in range(axis_fea.shape[0]):
        for ele in axis_fea[raw, :]:
            fea.append(ele)
    return fea


def axis_normalization(datalist, stage=1):
    normalized_data = []
    #datalist = np.array(datalist)
    for data in datalist:
        maximum = max(data)
        minimum = min(data)
        # print("maximum is:",maximum,"minimum is:",minimum)
        normalized_data.append([(item - minimum) / (maximum - minimum) * stage for item in data])
    return np.array(normalized_data)


def three_fuse(data):
    axis_num = int(data.shape[0] / 3)
    f_nd = []

    for f_in in range(axis_num):
        nd = []
        index = f_in * 3
        for i in range(data.shape[1]):
            d = data[:, i]
            fuse_data = math.sqrt(d[index] * d[index] + d[index + 1] * d[index + 1] + d[index + 2] * d[index + 2])
            nd.append(fuse_data)
        f_nd.append(nd)
    return f_nd

ModuleNotFoundError: No module named 'pyemd'

In [2]:
# target_path = "save_data/Vitural_NewData/scale_motion_0.8merge/pos/"
target_path = "save_data/Animation_record/pos/"
motion_name = ['ankle', 'highKnee', 'Kneekick', 'reverseLunge', 'sideCrunch', 'sidetoside', 'warmup']

for motion in motion_name:
    # pos_save_path = 'save_data/frompos_NewVirtualData/0.8merge/' + motion + '/'
    pos_save_path = 'save_data/Animation_record_pos_data/' + motion + '/'
    if not os.path.exists(pos_save_path):  # 判断所在目录下是否有该文件名的文件夹
        os.makedirs(pos_save_path)
    virtual_spline_data_path = glob.glob(target_path + '*' + motion + '*' + '*.csv')
    print(virtual_spline_data_path)
    temp_data = []
    for file in virtual_spline_data_path:
        # test_data_path = 'save_data/Vitural_NewData/scale_motion_1.1merge/pos/ReverseLunge_m_pos_merge_data.csv'
        # test_data_path = 'save_data/Vitural_NewData/scale_motion_1.1merge/pos/ankle_m_pos_merge_data.csv'
        modify_first_column(file)
        df = pd.read_csv(file,header=None, index_col=False)
        df = np.array(df).T
        time_list = df[0, :]
        for index in range(df.shape[0]-2):
        # for index in range(data.shape[0]):
            # x = data[:,index+2]
            x = df[index+2, :]
            # print(x)
            # print(x)
            second_pos = spline.spline_cal(time_list, x.tolist(), 1)
            re_x = second_pos.second_derivate()

            temp_data.append(re_x[50:len(re_x) - 50])  # 去掉头尾
        temp_data = np.array(temp_data)
        write_path = pos_save_path + motion + ".csv"
        with open(write_path, mode="w", encoding="utf-8", newline='') as f:
            csv_writer = csv.writer(f)
            for col in range(temp_data.shape[1]):
                write_data = temp_data[:, col]
                csv_writer.writerow(write_data)




['save_data/Animation_record/pos\\ankletap_m_pos_merge_data.csv']
['save_data/Animation_record/pos\\highKnee_m_pos_merge_data.csv']
['save_data/Animation_record/pos\\Kneekick_m_pos_merge_data.csv']
['save_data/Animation_record/pos\\reverseLunge_m_pos_merge_data.csv']
['save_data/Animation_record/pos\\sideCrunch_m_pos_merge_data.csv']
['save_data/Animation_record/pos\\sidetoside_m_pos_merge_data.csv']
['save_data/Animation_record/pos\\warmup_m_pos_merge_data.csv']


In [3]:

scale_list = ["0.5", "0.7", "0.9", "1.1", "1.3", "1.5"]
for ID in scale_list:
    # target_path = "save_data/Vitural_NewData/scale_motion_0.8merge/pos/"
    # target_path = "save_data/Vitural_New_New/scale_motion_" + ID + "merge/pos/"
    target_path = "save_data/Virtual_New_New_xy_18/scale_motion_" + ID + "merge/pos/"
    print(target_path)
    # motion_name = ['ankle', 'highKnee', 'Kneekick', 'reverseLunge', 'sideCrunch', 'sidetoside', 'warmup']
    motion_name = ['ankle', 'highKnee', 'reverseLunge', 'sideCrunch', 'sidetoside', 'warmup']
    # motion_name = ['reverseLunge']

    for motion in motion_name:
        # pos_save_path = 'save_data/frompos_NewVirtualData/0.8merge/' + motion + '/'
        # pos_save_path = 'save_data/pos_New_New_VirtualData/' + ID + 'merge/' + motion + '/'
        pos_save_path = 'save_data/pos_New_New_VirtualData_xy_18/' + ID + 'merge/' + motion + '/'
        if not os.path.exists(pos_save_path):  # 判断所在目录下是否有该文件名的文件夹
            os.makedirs(pos_save_path)
        virtual_spline_data_path = glob.glob(target_path + '*' + motion + '*' + '*.csv')
        print(virtual_spline_data_path)
        temp_data = []
        for file in virtual_spline_data_path:
            # test_data_path = 'save_data/Vitural_NewData/scale_motion_1.1merge/pos/ReverseLunge_m_pos_merge_data.csv'
            # test_data_path = 'save_data/Vitural_NewData/scale_motion_1.1merge/pos/ankle_m_pos_merge_data.csv'
            modify_first_column(file)
            df = pd.read_csv(file,header=None, index_col=False)
            df = np.array(df).T
            time_list = df[0, :]
            # for index in range(df.shape[0]-2):
            for index in range(df.shape[0]):
                # x = data[:,index+2]
                x = df[index, :]

                second_pos = spline.spline_cal(time_list, x.tolist(), 1)
                re_x = second_pos.second_derivate()

                temp_data.append(re_x[10:len(re_x) - 10])  # 去掉头尾
            temp_data = np.array(temp_data)
            write_path = pos_save_path + motion + ".csv"
            with open(write_path, mode="w", encoding="utf-8", newline='') as f:
                csv_writer = csv.writer(f)
                for col in range(temp_data.shape[1]):
                    write_data = temp_data[:, col]
                    csv_writer.writerow(write_data)
            modify_first_column(write_path)




save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos/
['save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos\\ankle_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos\\highKnee_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos\\reverseLunge_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos\\sideCrunch_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos\\sidetoside_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.5merge/pos\\warmup_m_pos_merge_data.csv']
save_data/Virtual_New_New_xy_18/scale_motion_0.7merge/pos/
['save_data/Virtual_New_New_xy_18/scale_motion_0.7merge/pos\\ankle_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.7merge/pos\\highKnee_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_motion_0.7merge/pos\\reverseLunge_m_pos_merge_data.csv']
['save_data/Virtual_New_New_xy_18/scale_m

In [4]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import accuracy_score
import glob
from sklearn.model_selection import train_test_split, KFold, cross_val_score, LeaveOneOut
from sklearn.manifold import TSNE
from sklearn import svm, tree
import warnings
warnings.filterwarnings("ignore")


In [20]:
# l_rf = RandomForestClassifier(n_estimators=100, random_state=42)
l_rf = RandomForestClassifier(n_estimators=100, random_state=42)
l_svc = svm.SVC(C=1.0, kernel='rbf')
# l_svc = svm.SVC(C=1000, kernel='rbf')
l_clftree = tree.DecisionTreeClassifier(criterion='entropy',random_state=42)

# loo = LeaveOneOut()

real_path = 'save_data/12-16-Realdataset-Xia/Dataset-ID-'

ID = [1, 2, 3, 4, 5, 6, 7]
label = [0, 1, 2, 3, 4, 5, 6, 7]
# encode_feauture = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
# encode_feauture = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


# Real_data_path = "save_data/RealData_Seg_byName_120/"
Real_data_path = "save_data/RealData_Seg_byName/"

# virtual_data_path = "save_data/Virtual_Seg_byScale_spline/"
# virtual_data_path = "save_data/Virtual_Seg_byScale/"
# virtual_data_path = "save_data/Pos_New_New_Virtual_Seg_byScale_spline/" # 新

# virtual_data_path_3 = "save_data/Pos_New_New_Virtual_Seg_byScale_spline5_120/"  #nice
# virtual_data_path = "save_data/Pos_New_New_Virtual_Seg_byScale_xy_60/" # 最新

virtual_data_path = "save_data/Pos_New_New_Virtual_Seg_byScale_xy_spline5_120/" # awsome !!!
# virtual_data_path_2 = "save_data/Pos_New_New_Virtual_Seg_byScale_xy_18_spline3_60/" # awsome !!!


# virtual_data_path_2 = "save_data/Pos_New_New_VirtualData_addPelvis_xyz_25_spline5_120/"

ori_data_path_2 = "save_data/Animation_record_pos_data_spline5_120"
# ori_data_path_2 = "save_data/Ori_motion_pos_data_spline5_120"

ori_data_path = 'save_data/Conv_Motion_acc_data_spline3_240/'


# virtual_data_path = "save_data/Pos_New_New_Virtual_Seg_byScale_xy_120/" # 最新
# virtual_data_path_3 = "save_data/Pos_New_New_Virtual_Seg_byScale_spline5_120/"
# virtual_data_path_3 = "save_data/Virtual_Seg_byScale_spline/"
# virtual_data_path = "save_data/Pos_New_New_Virtual_Seg_byScale_xyz_25_spline5_120/"
# virtual_data_path_3 = "save_data/Pos_New_New_VirtualData_addPelvis_xyz_25_spline3_240/"
virtual_data_path_2 = "save_data/Virtual_New_Conv_1230_spline4_240/"
virtual_data_path_6 = "save_data/Virtual_New_Conv_1230_spline3_240/"
virtual_data_path_7 = "save_data/Virtual_New_Conv_1230_spline5_240/"

virtual_data_path_5 = "save_data/Virtual_New_Conv_1231_spline3_240/"
virtual_data_path_8 = "save_data/Virtual_New_Conv_1231_spline4_240/"
virtual_data_path_9 = "save_data/Virtual_New_Conv_1231_spline5_240/"

virtual_data_path_10 = "save_data/Virtual_New_Conv_0101_spline4_240/"
virtual_data_path_11 = "save_data/Virtual_New_Conv_0101_spline3_240/"
virtual_data_path_12 = "save_data/Virtual_New_Conv_0101_spline5_240/"

virtual_data_path_13 = "save_data/Virtual_New_Conv_0101_2_spline3_240/"
virtual_data_path_14 = "save_data/Virtual_New_Conv_0101_2_spline4_240/"
virtual_data_path_15 = "save_data/Virtual_New_Conv_0101_2_spline5_240/"


virtual_data_path_3 = "save_data/Virtual_New_Conv_x_spline4_240/"
# virtual_data_path_4 = "save_data/Virtual_New_Conv_x_spline3_240/"
virtual_data_path_4 = "save_data/Virtual_New_Conv_notrans_spline3_240/"

virtual_motion_type = ['ankleTap', 'highKnee', 'reverseLunge', 'sideCrunch', 'sidetoside']

motion_name = ['ankle', 'highKnee', 'Kneekick', 'reverseLunge', 'sideCrunch', 'sidetoside', 'warmup']

human_name = ["Effy", "Leafy", "Nick", "Qin", "Tonii", "Xu", "Yamamoto"]
# human_name = ["Effy", "Leafy", "Nick", "Qin", "Xu", "Yamamoto"]
# scale_list = ["0.8", "0.9", "1.1","1.3", "1.2"]
# scale_list = ["0.5", "0.7", "0.8","0.9", "1.1", "1.2","1.3", "1.5"]
scale_list = ["0.5", "0.7", "0.9", "1.1", "1.3", "1.5"]
# scale_list = ["0.7", "0.9", "1.1", "1.3", "1.5"]
scale_list_conv = ["0", "1", "2", "3"]
scale_list_conv_2 = ["0", "1", "2"]

virtual_total_file = []
real_total_file = []
total_file = []

# for scale in scale_list:
#     virtual_total_file.append(virtual_data_path + scale)
#     total_file.append(virtual_data_path + scale)

for scale in scale_list_conv:
    virtual_total_file.append(virtual_data_path_3 + scale)
    total_file.append(virtual_data_path_3 + scale)
#
# for scale in scale_list_conv:
#     virtual_total_file.append(virtual_data_path_4 + scale)
#     total_file.append(virtual_data_path_4 + scale)

# total_file.append(ori_data_path)
# total_file.append(ori_data_path)
for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_2 + scale)
    total_file.append(virtual_data_path_2 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_5 + scale)
    total_file.append(virtual_data_path_5 + scale)


for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_6 + scale)
    total_file.append(virtual_data_path_6 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_7 + scale)
    total_file.append(virtual_data_path_7 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_8 + scale)
    total_file.append(virtual_data_path_8 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_9 + scale)
    total_file.append(virtual_data_path_9 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_10 + scale)
    total_file.append(virtual_data_path_10 + scale)
for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_11 + scale)
    total_file.append(virtual_data_path_11 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_12 + scale)
    total_file.append(virtual_data_path_12 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_13 + scale)
    total_file.append(virtual_data_path_13 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_14 + scale)
    total_file.append(virtual_data_path_14 + scale)

for scale in scale_list_conv_2:
    virtual_total_file.append(virtual_data_path_15 + scale)
    total_file.append(virtual_data_path_15 + scale)

virtual_data_path_scale_t = ["CorData-Seg/scale_0123_trans_spline3_240/", "CorData-Seg/scale_0123_trans_spline4_240/", "CorData-Seg/scale_0123_trans_spline5_240/"]
virtual_data_path_scale = ["CorData-Seg/scale_0123_spline3_240/", "CorData-Seg/scale_0123_pline4_240/", "CorData-Seg/scale_0123_spline5_240/"]
scale_list_2 = ["0.7", "1.3"]
# for scale in scale_list_2:
#     for path in virtual_data_path_scale:
#         virtual_total_file.append(path + scale)
#         total_file.append(path + scale)
# 
# for scale in scale_list_2:
#     for path in virtual_data_path_scale_t:
#         virtual_total_file.append(path + scale)
#         total_file.append(path + scale)


# total_file.append(ori_data_path_2)
# for scale in scale_list:
#     virtual_total_file.append(virtual_data_path_3 + scale)
#     total_file.append(virtual_data_path_3 + scale)

# for index in ID:
#     real_total_file.append(real_path + str(index))
#     total_file.append(real_path + str(index))
print(len(total_file))
for name in human_name:
    real_total_file.append(Real_data_path + name)
    total_file.append(Real_data_path + name)
print(total_file)


40
['save_data/Virtual_New_Conv_x_spline4_240/0', 'save_data/Virtual_New_Conv_x_spline4_240/1', 'save_data/Virtual_New_Conv_x_spline4_240/2', 'save_data/Virtual_New_Conv_x_spline4_240/3', 'save_data/Virtual_New_Conv_1230_spline4_240/0', 'save_data/Virtual_New_Conv_1230_spline4_240/1', 'save_data/Virtual_New_Conv_1230_spline4_240/2', 'save_data/Virtual_New_Conv_1231_spline3_240/0', 'save_data/Virtual_New_Conv_1231_spline3_240/1', 'save_data/Virtual_New_Conv_1231_spline3_240/2', 'save_data/Virtual_New_Conv_1230_spline3_240/0', 'save_data/Virtual_New_Conv_1230_spline3_240/1', 'save_data/Virtual_New_Conv_1230_spline3_240/2', 'save_data/Virtual_New_Conv_1230_spline5_240/0', 'save_data/Virtual_New_Conv_1230_spline5_240/1', 'save_data/Virtual_New_Conv_1230_spline5_240/2', 'save_data/Virtual_New_Conv_1231_spline4_240/0', 'save_data/Virtual_New_Conv_1231_spline4_240/1', 'save_data/Virtual_New_Conv_1231_spline4_240/2', 'save_data/Virtual_New_Conv_1231_spline5_240/0', 'save_data/Virtual_New_Conv_

In [22]:
class CustomLeaveOneOut:
    def __init__(self, start=7, end=13):
        self.start = start
        self.end = end
        self.current = start

    def __iter__(self):
        return self

    def __next__(self):
        if self.current > self.end:
            raise StopIteration
        test_indices = [self.current]
        train_indices = list(range(self.start, self.end + 1))
        train_indices.remove(self.current)
        self.current += 1
        # return list(range(47)) + train_indices, test_indices
        # return train_indices, test_indices

        # return list(range(8,9))+ list(range(2,6)), test_indices

        # return list(range(3,5)) + list(range(1)) + list(range(6,7)), test_indices
        # return train_indices, test_indices
        return list(range(40)), test_indices



# loo = CustomLeaveOneOut(start=6, end=11)
#
# for train_indices, test_indices in loo:
#     print("Train Indices:", train_indices)
#     print("Test Indices:", test_indices)

# Real_motion_type = ['ankle', 'highKnee', 'Kneekick', 'reverseLunge', 'sideCrunch', 'sidetoside', 'warmup']
# Real_motion_type = ['ankle', 'highKnee', 'reverseLunge', 'sideCrunch', 'sidetoside', ]
# Real_motion_type = ['ReverseLunge','HighKnee','ankle','Knee']
# Real_motion_type = ['ReverseLunge','HighKnee','Warm'] # persent高 目前获得提升 13混淆

# Real_motion_type = ['sidetoside','HighKnee','Warm'] # awsome!!!
# Real_motion_type = ['sidetoside','HighKnee','ReverseLunge']

# Real_motion_type = ['kneekick','reverselunge']

# Real_motion_type = ['ReverseLunge','HighKnee','sideCrunch'] # 相同
Real_motion_type = ['ReverseLunge','HighKnee','sidetoside'] # 相同awsome!!!!!!!!!!!
# Real_motion_type = ['ReverseLunge','HighKnee','sideCrunch'] 
# Real_motion_type = ['HighKnee','ReverseLunge','Kneekick'] # 相同awsome!!!!!
# Real_motion_type = ['ankle','sidetoside','Kneekick'] # 相同awsome!!!!!
# Real_motion_type = ['ReverseLunge','ankle','Kneekick'] # persent最高 目前获得提升

# Real_motion_type = ['sideCrunch','sidetoside','Ankle'] # awsome!!!
# Real_motion_type = ['sideCrunch','sidetoside','warm'] # pca improve!!!

# Real_motion_type = ['sideCrunch','sidetoside','ReverseLunge', 'highknee']
# Real_motion_type = ['warm','sidetoside','ReverseLunge', 'highknee']
# Real_motion_type = ['HighKnee','ReverseLunge','Kneekick'] # persent高 目前获得提升
encode_feauture = [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
# encode_feauture = [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
# Real_motion_type = ['Warm','HighKnee','sideCrunch','ankle'] # 相同awsome!!!!!
# Real_motion_type = ['warm','HighKnee','sidetoside'] # awsome

In [25]:
# loo = CustomLeaveOneOut(start=1, end=7)
# loo = CustomLeaveOneOut(start=7, end=13)
# loo = CustomLeaveOneOut(start=14, end=20)
# loo = CustomLeaveOneOut(start=8, end=14)
loo = CustomLeaveOneOut(start=40, end=46)
rf_predicted = []
svm_predicted = []
decisiontree_predicted = []
label_save_list = []
predict_SVM_save_list = []
predict_RF_save_list = []
predict_DT_save_list = []


# for train_index, test_index in loo.split(total_file):
#     print(train_index,test_index)
for train_index, test_index in loo:
    print(train_index,test_index)
    Data_X = []
    Label_X = []
    TestData_X = []
    TestLabel_X = []
    true_label = []
    for tmtrain in train_index:
        # print(tmtrain)
        subject = total_file[tmtrain]  # for each subject
        # print(subject)
        #subject_file = glob.glob(os.path.join(subject,'*.csv'))
        for i in range(len(Real_motion_type)):
            motion = Real_motion_type[i]
            motion_file = glob.glob(os.path.join(subject + '/' + '*' + motion + '*', '*.csv'))
            # motion_file = os.path.join(subject + '/' + 'motion', '*.csv')
            # motion_file = glob.glob(os.path.join(subject + '/' + 'motion/', '*.csv'))
            # print(subject + '/' +  motion )
            # print(motion_file)
            for motion_frame in motion_file:
                #print(motion_frame)
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [3,4,5,6,7,8,9,10,11,12,13,14])
                # df = pd.read_csv(motion_frame, index_col=False, header=None, usecols= [9,10,11,12,13,14])#1,2,3,4,5,6,7,8,9,10,11,12
                df = pd.read_csv(motion_frame, index_col=False, header=None, usecols= [9,10,11])#0,1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None, usecols= [9])#0,1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                df = np.array(df).T


                # timestamp = []
                # for t in range(df.shape[1]):
                #     timestamp.append(t*0.05)
                # timestamp = np.array(timestamp)

                # for k in range(df.shape[0]):
                #     df[k, :] = np_move_avg(df[k, :], 15, mode='same')

                # fuse three axis-data
                fuse_df = three_fuse(df)
                nor_df = axis_normalization(fuse_df)  #.tolist()
                # nor_df = axis_normalization(df)  #.tolist()

                axis_fea = []
                # rd = []
                # print(nor_df.shape)
                for raw in range(nor_df.shape[0]):
                # for raw in range(df.shape[0]):
                    tmd = nor_df[raw, :]

                    # resampling = spline.spline_cal(timestamp,tmd.tolist(),10)
                    #
                    # tmd = resampling.resample()
                    # print(tmd)

                    # tmd = df[raw, :]
                    # rd.append(tmd)
                    cal_fea = Calculate_Feature.Get_Feature(tmd, encode_feauture)
                    fea = cal_fea.cal_result()
                    for f in fea:
                        axis_fea.append(f)

                # print(axis_fea)

                Data_X.append(axis_fea)
                Label_X.append(label[i])

                # print(Label_X)

    Real_Data = np.array(Data_X)
    Real_Label = np.array(Label_X)
    # print(Real_Data.shape)
    # print(Real_Label.shape)

    # for i in range(Real_Data.shape[0]):
    #     Real_Data[i] = [0 if math.isnan(x) else x for x in Real_Data[i]]
    # print("real sample size before PCA is:", Real_Data.shape)
    #
    # pca = PCA(2)
    # Real_Data = pca.fit_transform(Real_Data)

    # tsne = TSNE(2)
    # Real_Data = tsne.fit_transform(Real_Data)

    print("real sample size is:", Real_Data.shape)
    l_rf.fit(Real_Data, Real_Label)
    l_svc.fit(Real_Data, Real_Label)
    l_clftree.fit(Real_Data, Real_Label)

    for tmtest in test_index:
        # print(tmtest)
        subject = total_file[tmtest]  # for each subject
        print(subject)
        #subject_file = glob.glob(os.path.join(subject,'*.csv'))
        for i in range(len(Real_motion_type)):
            motion = Real_motion_type[i]
            motion_file = glob.glob(os.path.join(subject + '/' + '*' + motion + '*', '*.csv'))
            for motion_frame in motion_file:
                #print(motion_frame)
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [3,4,5,6,7,8,9,10,11,12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [9,10,11])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [9])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [9,10,11,12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None)  #1,2,3,4,5,6,7,8,9,10,11,12
                df = np.array(df).T


                # timestamp = []
                # for t in range(df.shape[1]):
                #     timestamp.append(t*0.05)
                # timestamp = np.array(timestamp)

                #
                # for k in range(df.shape[0]):
                #     df[k, :] = np_move_avg(df[k, :], 20, mode='same')

                #fuse three axis-data
                fuse_df = three_fuse(df)
                nor_df = axis_normalization(fuse_df)  #.tolist()
                # nor_df = axis_normalization(df)  #.tolist()

                axis_fea = []
                # rd = []
                for raw in range(nor_df.shape[0]):
                # for raw in range(df.shape[0]):
                    tmd = nor_df[raw, :]
                    # tmd = df[raw, :]


                    # resampling = spline.spline_cal(timestamp,tmd.tolist(),10)
                    #
                    # tmd = resampling.resample()


                    # rd.append(tmd)
                    cal_fea = Calculate_Feature.Get_Feature(tmd, encode_feauture)
                    fea = cal_fea.cal_result()
                    for f in fea:
                        axis_fea.append(f)



                TestData_X.append(axis_fea)
                TestLabel_X.append(label[i])


    TestData = np.array(TestData_X)

    # for i in range(TestData.shape[0]):
    #     TestData[i] = [0 if math.isnan(x) else x for x in TestData[i]]

    TestLabel = np.array(TestLabel_X)
    label_save_list.append(TestLabel)

    # print("test sample size before PCA is:", TestData.shape)

    # pca = PCA(2)
    # TestData = pca.fit_transform(TestData)

    # tsne = TSNE(2)
    # TestData = tsne.fit_transform(TestData)

    print("test sample size is:", TestData.shape)


    predict_RF_save_list.append(l_rf.predict(TestData))
    predict_SVM_save_list.append(l_svc.predict(TestData))
    predict_DT_save_list.append(l_clftree.predict(TestData))


    rf_predicted.append(accuracy_score(TestLabel, l_rf.predict(TestData)))
    svm_predicted.append(accuracy_score(TestLabel, l_svc.predict(TestData)))
    decisiontree_predicted.append(accuracy_score(TestLabel, l_clftree.predict(TestData)))

    #true_label.append(TestLabel_X[0])

    print("*****")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39] [40]
real sample size is: (2876, 9)
save_data/RealData_Seg_byName/Effy
test sample size is: (66, 9)
*****
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39] [41]
real sample size is: (2876, 9)
save_data/RealData_Seg_byName/Leafy
test sample size is: (66, 9)
*****
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39] [42]
real sample size is: (2876, 9)
save_data/RealData_Seg_byName/Nick
test sample size is: (66, 9)
*****
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39] [43]
real sample size is: (2876, 9)
save_data/RealData_Seg_byName/Qin
test sa

In [27]:
print(rf_predicted)
print(svm_predicted)
print(decisiontree_predicted)
print(sum(rf_predicted) / len(rf_predicted))
print(sum(svm_predicted) / len(svm_predicted))
print(sum(decisiontree_predicted) / len(decisiontree_predicted))

[0.9393939393939394, 0.6666666666666666, 0.6060606060606061, 0.6212121212121212, 0.48484848484848486, 0.48484848484848486, 0.9242424242424242]
[0.9242424242424242, 0.6666666666666666, 0.6515151515151515, 0.6666666666666666, 0.4393939393939394, 0.4696969696969697, 0.9545454545454546]
[0.9242424242424242, 0.6060606060606061, 0.5909090909090909, 0.6515151515151515, 0.48484848484848486, 0.5303030303030303, 0.9242424242424242]
0.6753246753246752
0.6818181818181818
0.6731601731601732


3-5
0.7164502164502163
0.721861471861472
0.6536796536796537

3-6
0.6774891774891775
0.6785714285714286
0.6006493506493508

2-5
0.7608225108225108
0.7435064935064934
0.6958874458874459

4-6
0.6590909090909091
0.6374458874458874
0.5984848484848485

0 3-5
0.7727272727272727
0.7662337662337663
0.7132034632034632

0 1 3-5
0.7694805194805194
0.7683982683982684
0.7370129870129871

0 - 5
0.7510822510822511
0.7532467532467534
0.7045454545454547
0 - 6
0.7359307359307359
0.7683982683982683
0.7056277056277056

only 3
0.7521645021645021
0.7597402597402597
0.6818181818181819

only 4
0.7067099567099567
0.6547619047619048
0.6883116883116883


In [71]:
from sklearn.metrics import confusion_matrix

confusion_RF_list = []
confusion_SVM_list = []
confusion_DT_list = []
# total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for i in range(len(label_save_list)):
    confusion= confusion_matrix(label_save_list[i], predict_RF_save_list[i])
    confusion_RF_list.append(confusion)

    confusion= confusion_matrix(label_save_list[i], predict_SVM_save_list[i])
    confusion_SVM_list.append(confusion)

    confusion= confusion_matrix(label_save_list[i], predict_DT_save_list[i])
    confusion_DT_list.append(confusion)
    # print(confusion)

total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for cm in confusion_RF_list:
    total_confusion_matrix += cm
print("RF: ")
print(total_confusion_matrix)

total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for cm in confusion_SVM_list:
    total_confusion_matrix += cm
print("SVM: ")
print(total_confusion_matrix)

total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for cm in confusion_DT_list:
    total_confusion_matrix += cm
print("DT: ")
print(total_confusion_matrix)

#
# plt.scatter(TestData[:, 0], TestData[:, 1])
# plt.title('t-SNE Visualization')
# plt.show()

RF: 
[[ 27.  30.  97.]
 [ 15. 117.  22.]
 [ 73.  36.  45.]]
SVM: 
[[ 97.  37.  20.]
 [ 15. 114.  25.]
 [ 32.  55.  67.]]
DT: 
[[ 45.  26.  83.]
 [ 24. 102.  28.]
 [ 61.  45.  48.]]


In [129]:
Real_motion_type = ['ankle','sidetoside',]
# filter_list = [1,2,3,4]
filter_list = [1]
loo = CustomLeaveOneOut(start=1, end=7)
# loo = CustomLeaveOneOut(start=8, end=14)
# loo = CustomLeaveOneOut(start=12, end=18)
# loo = CustomLeaveOneOut(start=18, end=24)
rf_predicted = []
svm_predicted = []
decisiontree_predicted = []
label_save_list = []
predict_SVM_save_list = []
predict_RF_save_list = []
predict_DT_save_list = []


# for train_index, test_index in loo.split(total_file):
#     print(train_index,test_index)
for train_index, test_index in loo:
    print(train_index,test_index)
    Data_X = []
    Label_X = []
    TestData_X = []
    TestLabel_X = []
    true_label = []
    for tmtrain in train_index:
        # print(tmtrain)
        subject = total_file[tmtrain]  # for each subject
        # print(subject)
        #subject_file = glob.glob(os.path.join(subject,'*.csv'))
        for i in range(len(Real_motion_type)):
            motion = Real_motion_type[i]
            motion_file = glob.glob(os.path.join(subject + '/' + '*' + motion + '*', '*.csv'))
            # motion_file = os.path.join(subject + '/' + 'motion', '*.csv')
            # motion_file = glob.glob(os.path.join(subject + '/' + 'motion/', '*.csv'))
            # print(subject + '/' +  motion )
            # print(motion_file)
            for motion_frame in motion_file:
                #print(motion_frame)
                for filter_num in filter_list:
                    # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [3,4,5,6,7,8,9,10,11,12,13,14])
                    # df = pd.read_csv(motion_frame, index_col=False, header=None, usecols= [9,10,11,12,13,14])#1,2,3,4,5,6,7,8,9,10,11,12
                    # df = pd.read_csv(motion_frame, index_col=False, header=None, usecols= [9,10,11])#0,1,2,3,4,5,6,7,8,9,10,11,12
                    df = pd.read_csv(motion_frame, index_col=False, header=None, usecols= [9])#0,1,2,3,4,5,6,7,8,9,10,11,12
                    # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                    df = np.array(df).T


                    # timestamp = []
                    # for t in range(df.shape[1]):
                    #     timestamp.append(t*0.05)
                    # timestamp = np.array(timestamp)

                    for k in range(df.shape[0]):
                        df[k, :] = np_move_avg(df[k, :], filter_num, mode='same')

                    # fuse three axis-data
                    # fuse_df = three_fuse(df)
                    # nor_df = axis_normalization(fuse_df)  #.tolist()
                    nor_df = axis_normalization(df)  #.tolist()

                    axis_fea = []
                    # rd = []
                    # print(nor_df.shape)
                    for raw in range(nor_df.shape[0]):
                    # for raw in range(df.shape[0]):
                        tmd = nor_df[raw, :]

                        # resampling = spline.spline_cal(timestamp,tmd.tolist(),10)
                        #
                        # tmd = resampling.resample()
                        # print(tmd)

                        # tmd = df[raw, :]
                        # rd.append(tmd)
                        cal_fea = Calculate_Feature.Get_Feature(tmd, encode_feauture)
                        fea = cal_fea.cal_result()
                        for f in fea:
                            axis_fea.append(f)

                    # print(axis_fea)

                    Data_X.append(axis_fea)
                    Label_X.append(label[i])

                # print(Label_X)

    Real_Data = np.array(Data_X)
    Real_Label = np.array(Label_X)
    # print(Real_Data.shape)
    # print(Real_Label.shape)

    # for i in range(Real_Data.shape[0]):
    #     Real_Data[i] = [0 if math.isnan(x) else x for x in Real_Data[i]]
    # print("real sample size before PCA is:", Real_Data.shape)
    #
    # pca = PCA(2)
    # Real_Data = pca.fit_transform(Real_Data)

    # tsne = TSNE(2)
    # Real_Data = tsne.fit_transform(Real_Data)

    print("real sample size is:", Real_Data.shape)
    l_rf.fit(Real_Data, Real_Label)
    l_svc.fit(Real_Data, Real_Label)
    l_clftree.fit(Real_Data, Real_Label)

    for tmtest in test_index:
        # print(tmtest)
        subject = total_file[tmtest]  # for each subject
        print(subject)
        #subject_file = glob.glob(os.path.join(subject,'*.csv'))
        for i in range(len(Real_motion_type)):
            motion = Real_motion_type[i]
            motion_file = glob.glob(os.path.join(subject + '/' + '*' + motion + '*', '*.csv'))
            for motion_frame in motion_file:
                #print(motion_frame)
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [3,4,5,6,7,8,9,10,11,12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [9,10,11])  #1,2,3,4,5,6,7,8,9,10,11,12
                df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [9])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None,  usecols= [9,10,11,12,13,14])  #1,2,3,4,5,6,7,8,9,10,11,12
                # df = pd.read_csv(motion_frame, index_col=False, header=None)  #1,2,3,4,5,6,7,8,9,10,11,12
                df = np.array(df).T


                # timestamp = []
                # for t in range(df.shape[1]):
                #     timestamp.append(t*0.05)
                # timestamp = np.array(timestamp)

                #
                # for k in range(df.shape[0]):
                #     df[k, :] = np_move_avg(df[k, :], 30, mode='same')

                #fuse three axis-data
                # fuse_df = three_fuse(df)
                # nor_df = axis_normalization(fuse_df)  #.tolist()
                nor_df = axis_normalization(df)  #.tolist()

                axis_fea = []
                # rd = []
                for raw in range(nor_df.shape[0]):
                # for raw in range(df.shape[0]):
                    tmd = nor_df[raw, :]
                    # tmd = df[raw, :]


                    # resampling = spline.spline_cal(timestamp,tmd.tolist(),10)
                    #
                    # tmd = resampling.resample()


                    # rd.append(tmd)
                    cal_fea = Calculate_Feature.Get_Feature(tmd, encode_feauture)
                    fea = cal_fea.cal_result()
                    for f in fea:
                        axis_fea.append(f)



                TestData_X.append(axis_fea)
                TestLabel_X.append(label[i])


    TestData = np.array(TestData_X)

    # for i in range(TestData.shape[0]):
    #     TestData[i] = [0 if math.isnan(x) else x for x in TestData[i]]

    TestLabel = np.array(TestLabel_X)
    label_save_list.append(TestLabel)

    # print("test sample size before PCA is:", TestData.shape)

    # pca = PCA(2)
    # TestData = pca.fit_transform(TestData)

    # tsne = TSNE(2)
    # TestData = tsne.fit_transform(TestData)

    print("test sample size is:", TestData.shape)


    predict_RF_save_list.append(l_rf.predict(TestData))
    predict_SVM_save_list.append(l_svc.predict(TestData))
    predict_DT_save_list.append(l_clftree.predict(TestData))


    rf_predicted.append(accuracy_score(TestLabel, l_rf.predict(TestData)))
    svm_predicted.append(accuracy_score(TestLabel, l_svc.predict(TestData)))
    decisiontree_predicted.append(accuracy_score(TestLabel, l_clftree.predict(TestData)))

    #true_label.append(TestLabel_X[0])

    print("*****")

[0] [1]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Effy
test sample size is: (44, 20)
*****
[0] [2]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Leafy
test sample size is: (44, 20)
*****
[0] [3]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Nick
test sample size is: (44, 20)
*****
[0] [4]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Qin
test sample size is: (44, 20)
*****
[0] [5]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Tonii
test sample size is: (44, 20)
*****
[0] [6]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Xu
test sample size is: (44, 20)
*****
[0] [7]
real sample size is: (34, 20)
save_data/RealData_Seg_byName/Yamamoto
test sample size is: (44, 20)
*****


In [130]:
print(rf_predicted)
print(svm_predicted)
print(decisiontree_predicted)
print()
print(sum(rf_predicted) / len(rf_predicted))
print(sum(svm_predicted) / len(svm_predicted))
print(sum(decisiontree_predicted) / len(decisiontree_predicted))

[0.6818181818181818, 0.5, 0.8636363636363636, 0.5, 0.5, 1.0, 0.5]
[0.7727272727272727, 0.8863636363636364, 1.0, 0.5227272727272727, 0.1590909090909091, 1.0, 1.0]
[0.5, 0.5, 0.5, 0.5, 0.5, 0.5909090909090909, 0.5]

0.6493506493506492
0.762987012987013
0.512987012987013


In [41]:
from sklearn.metrics import confusion_matrix

confusion_RF_list = []
confusion_SVM_list = []
confusion_DT_list = []
# total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for i in range(len(label_save_list)):
    confusion= confusion_matrix(label_save_list[i], predict_RF_save_list[i])
    confusion_RF_list.append(confusion)

    confusion= confusion_matrix(label_save_list[i], predict_SVM_save_list[i])
    confusion_SVM_list.append(confusion)

    confusion= confusion_matrix(label_save_list[i], predict_DT_save_list[i])
    confusion_DT_list.append(confusion)
    # print(confusion)

total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for cm in confusion_RF_list:
    total_confusion_matrix += cm
print("RF: ")
print(total_confusion_matrix)

total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for cm in confusion_SVM_list:
    total_confusion_matrix += cm
print("SVM: ")
print(total_confusion_matrix)

total_confusion_matrix = np.zeros((len(Real_motion_type), len(Real_motion_type)))
for cm in confusion_DT_list:
    total_confusion_matrix += cm
print("DT: ")
print(total_confusion_matrix)

#
# plt.scatter(TestData[:, 0], TestData[:, 1])
# plt.title('t-SNE Visualization')
# plt.show()

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) (3,3) 